# Generated by Django 4.1 on 2022-08-31 21:45

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="https://drive.google.com/file/d/1zAIlcsheJqK3f3HembRs_RP-_3A1TLJp/view?usp=sharing",
                upload_to=accounts.models.get_upload_path,
            ),
        ),
    ]
