# Generated by Django 4.1 on 2022-08-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="views",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
